# Generated by Django 2.1.8 on 2020-04-25 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(max_length=10, primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, max_length=150, null=True)),
                ('sobrenome', models.TextField(max_length=500)),
                ('senha', models.TextField(blank=True, max_length=500)),
            ],
        ),
    ]
